# This is a basic workflow to help you get started with Actions

name: build-and-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Install H2 database
      - name: Liquibase Init Start H2 Action
      # You may pin to the exact commit or the version.
      # uses: liquibase-github-actions/init-start-h2@0bc68ec9e912a925ff5603bed8cbf68afb38d4c0
      - uses: liquibase-github-actions/init-start-h2@v4.31.1
        with:
          # Network address to bind to
          bindAddress: # optional
          # Port to run h2 database on
          dbPort: # optional
          # When set to true, Liquibase initiates the H2 database in a new thread without blocking, allowing use within the flow command. Regardless of the parameter setting, data stored in the H2 database is cleared when the JVM exits, such as at the end of the flow command.
          detached: # optional
          # Whether to open a browser to the database"s web interface
          launchBrowser: # optional
          # Password to use for created h2 user
          password: # optional
          # Username to create in h2
          username: # optional
          # Port to run h2"s web interface on
          webPort: # optional
          # If true, a subset of the MdcKeys, as defined by product, will be set to empty strings upon system startup.
          addEmptyMdcValues: # optional
          # Allows duplicated changeset identifiers without failing Liquibase execution.
          allowDuplicatedChangesetIdentifiers: # optional
          # If true, drop and recreate a view instead of replacing it.
          alwaysDropInsteadOfReplace: # optional

